trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
    displayName: 'Use Node.js 8.12'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npm run compile
    displayName: 'Compile'
